In [7]:
import numpy as np


In [9]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [13]:
x=np.arange(1,10,2)

In [19]:
x
print(x)
x[0::2]

[1 3 5 7 9]


array([1, 5, 9])

In [38]:
x = str(123412)
np.floor(len(x)/2)

3.0

In [52]:
def palindrome(n):
    n = str(n)
    for i in range(0,int(np.floor(len(n)/2))):
        if n[i] != n[len(n)-i-1]:
            return False
            break
    return True
       
            


In [89]:
palindrome(920*940)

False

In [77]:
a = 1000
b = 1000
while a > 100:
    while b > 100:
        x = a*b
        if palindrome(x):
            print(b)
        b-=1
    a-=1

            

In [159]:
x = 1000
y = 1000
max = 0
while x > 800:
    y = 1000
    while y > 500:
        if palindrome(x*y):
            if x*y > max :
                max = x*y
        y-=1
    x-=1
print(max)


906609


In [138]:
for x in np.arange(999,100,-1):
    for y in np.arange(999,100,-1):
            if palindrome(x*y):
                print(x*y)
                print([x,y])
max(1,2)
          
                

580085
[995, 583]
514415
[995, 517]
906609
[993, 913]
119911
[991, 121]
282282
[987, 286]
141141
[987, 143]
853358
[982, 869]
650056
[979, 664]
601106
[979, 614]
592295
[979, 605]
543345
[979, 555]
485584
[979, 496]
436634
[979, 446]
378873
[979, 387]
329923
[979, 337]
408804
[978, 418]
204402
[978, 209]
623326
[977, 638]
525525
[975, 539]
299992
[974, 308]
469964
[971, 484]
886688
[968, 916]
804408
[968, 831]
698896
[968, 722]
631136
[968, 652]
616616
[968, 637]
443344
[968, 458]
428824
[968, 443]
270072
[968, 279]
255552
[968, 264]
828828
[966, 858]
414414
[966, 429]
487784
[964, 506]
180081
[963, 187]
888888
[962, 924]
666666
[962, 693]
444444
[962, 462]
222222
[962, 231]
348843
[961, 363]
770077
[959, 803]
653356
[958, 682]
855558
[957, 894]
807708
[957, 844]
696696
[957, 728]
648846
[957, 678]
531135
[957, 555]
489984
[957, 512]
372273
[957, 389]
324423
[957, 339]
165561
[957, 173]
117711
[957, 123]
577775
[955, 605]
723327
[953, 759]
649946
[953, 682]
272272
[952, 286]
219912
[95

68186
[662, 103]
98489
[661, 149]
137731
[659, 209]
282282
[658, 429]
209902
[658, 319]
90009
[657, 137]
79497
[657, 121]
72927
[657, 111]
438834
[654, 671]
273372
[654, 418]
89598
[654, 137]
416614
[653, 638]
631136
[652, 968]
408804
[652, 627]
76167
[651, 117]
471174
[649, 726]
432234
[649, 666]
374473
[649, 577]
335533
[649, 517]
277772
[649, 428]
238832
[649, 368]
73337
[649, 113]
78287
[647, 121]
71817
[647, 111]
611116
[646, 946]
588885
[645, 913]
81018
[643, 126]
528825
[641, 825]
84348
[639, 132]
623326
[638, 977]
489984
[638, 768]
464464
[638, 728]
416614
[638, 653]
280082
[638, 439]
257752
[638, 404]
232232
[638, 364]
209902
[638, 329]
86768
[638, 136]
616616
[637, 968]
595595
[637, 935]
525525
[637, 825]
434434
[637, 682]
343343
[637, 539]
252252
[637, 396]
161161
[637, 253]
93639
[637, 147]
85358
[637, 134]
77077
[637, 121]
70707
[637, 111]
447744
[636, 704]
258852
[636, 407]
509905
[635, 803]
522225
[633, 825]
215512
[632, 341]
589985
[631, 935]
87078
[631, 138]
456654
[62

87478
[382, 229]
129921
[381, 341]
86868
[381, 228]
75057
[381, 197]
43434
[381, 114]
83538
[378, 221]
48384
[378, 128]
232232
[377, 616]
84448
[377, 224]
63336
[377, 168]
42224
[377, 112]
297792
[376, 792]
44744
[376, 119]
57375
[375, 153]
52125
[375, 139]
272272
[374, 728]
266662
[374, 713]
231132
[374, 618]
225522
[374, 603]
219912
[374, 588]
86768
[374, 232]
45254
[374, 121]
41514
[374, 111]
37673
[373, 101]
270072
[372, 726]
212212
[371, 572]
99799
[371, 269]
198891
[369, 539]
117711
[369, 319]
99999
[369, 271]
89298
[369, 242]
81918
[369, 222]
71217
[369, 193]
238832
[368, 649]
88688
[368, 241]
81618
[366, 223]
59495
[365, 163]
52925
[365, 145]
50005
[365, 137]
292292
[364, 803]
272272
[364, 748]
252252
[364, 693]
232232
[364, 638]
212212
[364, 583]
88088
[364, 242]
86268
[364, 237]
84448
[364, 232]
82628
[364, 227]
80808
[364, 222]
65156
[364, 179]
63336
[364, 174]
61516
[364, 169]
44044
[364, 121]
42224
[364, 116]
40404
[364, 111]
348843
[363, 961]
270072
[363, 744]
255552
[363

57375
[225, 255]
52425
[225, 233]
84448
[224, 377]
65856
[224, 294]
48384
[224, 216]
29792
[224, 133]
188881
[223, 847]
98789
[223, 443]
81618
[223, 366]
59095
[223, 265]
56865
[223, 255]
210012
[222, 946]
81918
[222, 369]
80808
[222, 364]
63936
[222, 288]
62826
[222, 283]
61716
[222, 278]
60606
[222, 273]
45954
[222, 207]
44844
[222, 202]
43734
[222, 197]
42624
[222, 192]
41514
[222, 187]
40404
[222, 182]
27972
[222, 126]
26862
[222, 121]
25752
[222, 116]
24642
[222, 111]
23532
[222, 106]
22422
[222, 101]
83538
[221, 378]
54145
[221, 245]
26962
[221, 122]
90009
[219, 411]
79497
[219, 363]
72927
[219, 333]
60006
[219, 274]
49494
[219, 226]
42924
[219, 196]
30003
[219, 137]
89598
[218, 411]
84148
[218, 386]
64746
[218, 297]
76167
[217, 351]
43834
[217, 202]
82728
[216, 383]
67176
[216, 311]
63936
[216, 296]
48384
[216, 224]
29592
[216, 137]
55255
[215, 257]
53535
[215, 249]
51815
[215, 241]
65056
[214, 304]
45154
[214, 211]
25252
[214, 118]
92229
[213, 433]
84348
[213, 396]
76467
[213, 

2

In [95]:
for y in range(10,100):
    print(y)

10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [135]:
for y in np.arange(999,100,-1):
    for x in np.arange(999,100,-1):
        if x == 996 and y == 994:
            print(x)
            print(y)
            
            
print(y)
print(x)

996
994
101
101


In [146]:
def c():
	max = maxI = maxJ = 0
	i = 999
	j = 990
	while (i > 100):
		j = 990
		while (j > 100):
			product = i * j
			if (product > max):
				productString = str(product)
				if (productString == productString[::-1]):
					max = product
					maxI = i
					maxJ = j
			j -= 11
		i -= 1
	return max, maxI, maxJ

In [147]:
c()

(0, 0, 0)

In [157]:
for n in range(2, 10): 
    for x in range(2, n):
        if n % x == 0:
            print(n, 'equals', x, '*', n//x)
            break
    else:
        print(n, 'is a prime number')

2 is a prime number
3 is a prime number
4 equals 2 * 2
5 is a prime number
6 equals 2 * 3
7 is a prime number
8 equals 2 * 4
9 equals 3 * 3
